[package]
name = "melt"
version = "2.1.5"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"
repository = "https://github.com/fenhl/melt"

[profile.release]
lto = true
strip = true

[dependencies]
is-terminal = "0.4"
chrono-tz = "0.8"
itertools = "0.11"
thiserror = "1"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["std"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel" #TODO publish on crates.io?
branch = "main"
default-features = false
