[package]
name = "melt"
version = "2.0.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"
repository = "https://github.com/fenhl/melt"

[dependencies]
atty = "0.2"
chrono = "0.4"
chrono-tz = "0.5"
futures = "0.3"
itertools = "0.10"
paw = "1"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.tokio]
version = "1"
features = ["io-std", "io-util"]

[dependencies.tokio-stream]
version = "0.1"
features = ["io-util"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel" #TODO publish on crates.io?
branch = "main"
