[package]
name = "melt"
version = "2.1.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"
repository = "https://github.com/fenhl/melt"

[profile.release]
lto = true
strip = true

[dependencies]
atty = "0.2"
chrono-tz = "0.8"
futures = "0.3"
itertools = "0.10"
paw = "1"
thiserror = "1"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["std"]

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["io-std", "io-util"]

[dependencies.tokio-stream]
version = "0.1"
features = ["io-util"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel" #TODO publish on crates.io?
branch = "main"
